# Generated by Django 4.1.3 on 2022-11-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expenses_income_member_delete_customer_delete_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
